server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  #    password: zzh1995@
#    password: zzh1995@
mybatis:
  mapper-locations:
    - classpath:/mapper/**/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

logging:
  level:
    com.example.tiny_demo: debug
#    com.example.tiny_demo.modules.ums: debug
#    com.example.tiny_demo.security: debug

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
