server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true


spring:
  datasource:
    url: jdbc:mysql://db:3306/mall_tiny?serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://localhost:3306/mall_tiny?serverTimezone=Asia/Shanghai
    username: reader
#    username: root
    password: 123456
  #    password: zzh1995@
  redis:
#    host: localhost
    host: redis
    database: 1
    port: 6379
    password:
    timeout: 100

mybatis:
  mapper-locations:
    - classpath:/mapper/**/*.xml

logging:
  file:
#    path: ./logs
    path: /var/logs
  level:
        com.example.tiny_demo: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,CTT
##    com.example.tiny_demo.modules.ums.service: info
#    com.example.tiny_demo.security.component : debug

## 自定义的配置属性
redis:
  database: tiny-demo
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7 即7天)
  tokenHead: 'Bearer '  #JWT负载中拿到开头


secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout

